Add documentation for label_limits option
nhs-r-community/NHSRplotthedots pull request #214
Opened 2024-08-06 01:15 UTC by francisbarton

- [ ] added unit tests and checked code coverage with `covr::report()` (should aim for 100%)
- [x] ran `devtools::document()`
- [x] ran `lintr::lint_package()` and resolved all lint warnings and notes
- [x] ran `styler::style_pkg()` to make sure code matches the style guidelines
- [x] ran R-CMD CHECK and resolved all issues

Added section to README that illustrates the `label_limits` option.
Also tidied up a few syntax bits in one of the test files (not relevant to the above) to remove the `1:20` style shorthand for creating numeric vectors (in particular circumstances this can cause unexpected behaviours and it's safer in general to use `seq()`).

Closes issue #192

2024-08-08 14:15 UTC, ThomUK requested changes
Thanks for contributing this Fran.  
It's a pretty big PR covering a lot of different change.  Would it be possible to break this up and link separate PRs to individual issues, which will make it much easier to safely merge changes? Some may be changes to satisfy the linter?
I think this PR currently includes:
* Documentation of label limits functionality (including adding you to authors list, all good)
* Github action Rmarkdown rendering changes
* Linting rule changes
* Refactoring of create_ggplot function
* Changes to hex logo code
* A big diff for some changes to unit tests, which is difficult to check
* Vignette refactoring

Also paging @tomjemmett for a 2nd pair of eyes.  I'm conscious this package's functionality is important to many people now.

2024-08-08 17:17 UTC, francisbarton commented
Thanks Tom, appreciate you taking a look and leaving such a constructive comment.
I tried really hard to keep the PR focused and clean but for some reason - some unwitting action of mine that I don't fully understand - the PR kept getting cluttered with all the other irrelevant commits that belong to other PRs.

I appreciate the need for a small set of diffs that can be properly reviewed, so I will try once again!

2024-08-21 15:11 UTC, francisbarton commented
There should have been some changes to the README associated with this PR but I think the relevant commits already got merged in, in #215 ... apologies again for the mess, it was unintentional!

2024-08-21 22:15 UTC, tomjemmett approved these changes

2024-08-21 22:17 UTC, tomjemmett approved these changes

2024-08-21 22:20 UTC, merged