Added example to README
nhs-r-community/NHSRplotthedots pull request #49
Opened 2021-07-22 20:16 UTC by chrismainey

Added example based on the vignette, and tweaked a bit of the README file.  Closes #18 .

2021-07-23 11:59 UTC, chrismainey commented
@Lextuga007 Would you mind reviewing this before merging please?

2021-07-24 03:45 UTC, tomjemmett requested changes
very minor change from me! though happy to be overruled on it

2021-07-24 03:45 UTC, tomjemmett commented on README.Rmd
>  # install.packages("remotes")
I would suggest we uncomment out this line - one issue I was made aware / reminded of recently was older versions of `{remotes}` would only pull from master, but now it will pull the HEAD reference instead. Uncommenting this line will cause the package to be reinstalled if it is old :-)

2021-07-24 03:46 UTC, tomjemmett commented on README.Rmd
> +```r
is this valid rmarkdown syntax? I've only ever used ```{r}, didn't know you could skip the brackets!

2021-07-24 06:58 UTC, chrismainey commented on README.Rmd
> +```r
I learnt this one from @Lextuga007 .  Formats as code but downs run it. That said: setting it as normal with eval=FALSE would also do the same thing. Ideally don't want to reinstall the package when building the README.

2021-07-24 11:12 UTC, tomjemmett commented on README.Rmd
> +```r
ah, cool. Yeah you don't want this to run when running knitting. I've always used eval=FALSE but if this works too 👍

2021-07-26 16:05 UTC, Lextuga007 commented on README.Rmd
>  # install.packages("remotes")
That's fine by me. I changed this to development as that's where the package was being run from but this is being released soon to main so happy to run from there and avoid potential issues with {remotes}

2021-07-26 16:07 UTC, Lextuga007 commented on README.Rmd
>  # install.packages("remotes")
By resolving the conversation does that accept the code change?

2021-07-26 16:09 UTC, Lextuga007 approved these changes

2021-07-26 16:16 UTC, Lextuga007 approved these changes

2021-07-26 17:38 UTC, tomjemmett commented on README.Rmd
>  # install.packages("remotes")
ah, not exactly. I made a suggestion to change the code, but didn't make the change. Marking as resolved is more saying "yeah I did what was asked!"

2021-07-27 07:47 UTC, Lextuga007 commented on README.Rmd
>  # install.packages("remotes")
I think a note is required for uncommenting this line as the standard practice I've seen for using remotes or devtools is to comment it out. I'm guessing to do this I would need to update the pull request with my own addition or is there another way to update Chris' changes?

2021-07-27 09:25 UTC, tomjemmett commented on README.Rmd
>  # install.packages("remotes")
@chrismainey would need to update rather than you as this is coming from a forked repo. I think the common practice I've seen is to comment it out, but as mentioned above, if people have an older version of remotes, this line will fail to run in a very non-obvious way. Having that line uncommented may trigger someone to copy/paste and force the package to update :-)

2021-07-27 15:40 UTC, chrismainey commented
Closing and opening a new one with updated to new standards.

2021-07-27 15:40 UTC, closed without merging